name: Add File

on:
  push:
    branches:
      - gh-pages

jobs:
  add-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add file
      run: echo "your-file-content" > your-file-name.txt
