name: download-google-search-file
on:
  push:
    branches:
      - gh-pages
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: download-file
      run: |
        wget https://github.com/StudyingLover/StudyingLover.github.io/blob/main/google22e70b1e2925e4e9.html
